### ISSUE TITLE
Issue with GEOMFUM_DATA_DIR Environment Variable

### ISSUE THREAD

**Issue by GiLonga** [luisfpereira/geomfum#1]
Hey Luis, 
I encountered an issue where the `GEOMFUM_DATA_DIR` environment variable was not properly set when I ran:

```python
'os.environ["GEOMFUM_DATA_DIR"]'
```
I fixed it in my activate.bat file by adding: 

```batch
set GEOMFUM_DATA_DIR=%SCRIPT_DIR%\geomfum\data
```
Is it expected?

Thanks,
Giorgio

**Comment by luisfpereira** [comment]
Hi @GiLonga, I'm very glad to see your first issue here!

Yes, that's the expected behavior.
Since for now, I don't want to store data in the repo, I'm assuming users download the data (available e.g. in `pyfm`), store it wherever they want, and create an environment variable that indicates that folder (`set` in windows; `export` in linux).

This was just a quick dirty hack to have some notebooks running though.
I'm creating an action in our project to actually download/load the data if not yet available in the user machine, so this step becomes more clear.

Thank you for pointing it out!
